
BASE_STATION_RANGE = 300  # meters
MOBILE_RANGE = 75    # meters

SATELLITE_DISTANCE = 300000  # meters

TERRAIN_SIZE = 500  # meters^2


NUMBER_OF_USERS = 50
NUMBER_OF_CONTENTS = 500000


MOBILE_CACHE_CAPACITY       = 25       # Megabytes
BASE_STATION_CACHE_CAPACITY = 1000     # Megabytes
SATELLITE_CACHE_CAPACITY    = 4000  # Megabytes


CONTENT_SIZE = 5  # Megabytes
ZIPF_PARAMETER = 1.2  # ???

